### ISSUE TITLE
WLED crashing with Home Assistant integration enabled

### ISSUE THREAD

**Issue by klaidaslekavicius** [Aircoookie/WLED#2719]
### What happened?

Hello! 

I've been trying to configure WLED native integration for Home Assistant for a few days now. I have three ESP8266 controllers in my house controlling different LED trips (300 LEDs for every controller), although two of them are configured to work in Sync mode. Before setting up HA in my house I had zero issues or crashes over the time course of ~4 months.

After configuring the WLED integration I started noticing random WLED crashes. WLED goes back to its default setting, HA reports device as unavailable for a certain period of time, WLED UI becomes unavailable for ~10 seconds before it reconnects back to my network. Eventually it comes back to live on HA as well, although this happens more often as I start toggling different settings.

<img width="316" alt="Screenshot 2022-07-17 at 21 36 57" src="https://user-images.githubusercontent.com/36949465/179420060-358b5fb3-79e8-4b9e-bac9-158a8975777c.png">

So far I tried:

- Removing the integration from HA completely and going through the setup again
- Disabled WIFI Sleep in WLED Wifi Settings (thought it might be a networking issue)
- Assigned a static IP for WLED controller and reserved that IP on my router (again, I thought it might be a networking issue, but from the error it seems that WLED integration fails to decode the JSON payload)

### To Reproduce Bug

I went through the usual WLED integration setup procedure, didn't do anything unusual. HA automatically discovers WLED entity (I also tried manual option). Yet after making WLED available through HA I encounter random crashes.

### Expected Behavior

WLED shouldn't crash with HA integration configured and should retain the connection.

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.1 (build number: 2203150)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Relevant log/trace output

```shell
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/wled/coordinator.py", line 104, in _async_update_data
    device = await self.wled.update(full_update=not self.last_update_success)
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wled/wled.py", line 238, in update
    if not (data := await self.request("/json")):
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wled/wled.py", line 197, in request
    response_data = await response.json()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 2737: invalid start byte
```

### Anything else?

<img width="993" alt="Screenshot 2022-07-17 at 21 46 13" src="https://user-images.githubusercontent.com/36949465/179420397-19ac69d4-f94e-4c89-acae-a4015a03a1d4.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by klaidaslekavicius** [comment]
Actually, I think this might be my configuration issue. I'll try to re-validate for any UTF-8 decoding errors and will monitor a bit more
