### ISSUE TITLE
WLED 0.15.0 bX --- Home Assistant error when Preset is set to only toggle segment

### ISSUE THREAD

**Issue by KrX3D** [Aircoookie/WLED#4236]
### What happened?

Hello,

i got one esp32 which i use to toggle the light on and off, with an relay since its just an 12v warmwhite led strip.

I set the led output to the relay pin:

![image](https://github.com/user-attachments/assets/615a65f8-d746-403b-82f2-7846fe8bb0d0)

and im useing as preset 

{"seg":[{"id":0,"on":"t"}]}

and 

{"seg":[{"id":1,"on":"t"}]}

and that works. i found this solution here:

https://wled.discourse.group/t/two-buttons-and-three-segments-switching/8062/3

but i cant add it to home assistant, it doesnt auto discover and when i enter the IP address i get an error in the log

the error is:

```
Logger: homeassistant
Quelle: components/wled/config_flow.py:117
Erstmals aufgetreten: 19:51:44 (1 Vorkommnisse)
Zuletzt protokolliert: 19:51:44

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 135, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1322, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wled/config_flow.py", line 81, in async_step_zeroconf
    self.discovered_device = await self._async_get_device(discovery_info.host)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wled/config_flow.py", line 117, in _async_get_device
    return await wled.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wled/wled.py", line 268, in update
    self._device = Device.from_dict(data)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in __mashumaro_from_dict__
  File "/usr/local/lib/python3.12/site-packages/wled/models.py", line 762, in __pre_deserialize__
    int(preset_id): preset | {"preset_id": int(preset_id)}
    ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'seg'
```

### To Reproduce Bug

- set as led output to on/off and pick an relay pin
- set as preset :
                        {"seg":[{"id":0,"on":"t"}]}
                         and 
                        {"seg":[{"id":1,"on":"t"}]}
- try to add it to home assistant.

### Expected Behavior

addint to home assistant should work.

or an better way to toggle on/off and relay should be present. the usermod multi_relay want working how i wanted it for my purpose

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.15.0.-b7, wasnt also working with beta version before, didnt thest 0.14

### Which microcontroller/board are you seeing the problem on?

ESP32, ESP32-S2, ESP32-C3

### Relevant log/trace output

```shell
Logger: homeassistant
Quelle: components/wled/config_flow.py:117
Erstmals aufgetreten: 19:51:44 (1 Vorkommnisse)
Zuletzt protokolliert: 19:51:44

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 135, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1322, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wled/config_flow.py", line 81, in async_step_zeroconf
    self.discovered_device = await self._async_get_device(discovery_info.host)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wled/config_flow.py", line 117, in _async_get_device
    return await wled.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wled/wled.py", line 268, in update
    self._device = Device.from_dict(data)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in __mashumaro_from_dict__
  File "/usr/local/lib/python3.12/site-packages/wled/models.py", line 762, in __pre_deserialize__
    int(preset_id): preset | {"preset_id": int(preset_id)}
    ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'seg'
```

### Anything else?

Home Assistant

Core
2024.10.4
Supervisor
2024.10.3
Operating System
13.2
Frontend
20241002.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
I am not familiar with home assistant, but if this is a WLED bug, you need to provide wled debug info, not HA debug info. also: there is a HA channel on discord for questions.

**Comment by softhack007** [comment]
@KrX3D I think this is a homeassistant bug.
HA WLED seems to have problems with presets that contain special values. If your preset works as expected in WLED, then your error is a problem in in HomeAssistant.

https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+wled%22
